name: Prettier
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout file java
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: reformat kode
        uses: creyD/prettier_action@v3.3
        with:
          prettier_option: --write **/*.java
          commit_message: 'reformat kode java'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
